### ISSUE TITLE
could not compile `packed_simd`

### ISSUE THREAD

**Issue by uk0** [rajasekarv/vega#122]
error[E0432]: unresolved import crate::arch::x86_64::_mm_movemask_pi8
--> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd-0.3.3/src/codegen/reductions/mask/x86/sse.rs:47:21

https://asciinema.org/a/0EOIzjxOI9UcyQLohN9Lwgvb5

**Comment by clumsy456** [comment]
I've met the same problem as you.

**Comment by zgjhust** [comment]
the same problem +1

**Comment by rajasekarv** [comment]
may I know the exact rust nightly version you are using and the OS version and if possible, system information?

**Comment by zgjhust** [comment]
OS version & rust toolchain version as follows:
`
zhougj@DESKTOP-0077C7K:~/Develop/rust-test/vega$ cat /etc/issue
Ubuntu 18.04.4 LTS \n \l

zhougj@DESKTOP-0077C7K:~/Develop/rust-test/vega$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/zhougj/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.50.0-nightly (c919f490b 2020-11-17)

zhougj@DESKTOP-0077C7K:~/Develop/rust-test/vega$ uname -a
Linux DESKTOP-0077C7K 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
`

compile aborted with following error info:
`
error[E0432]: unresolved import `crate::arch::x86_64::_mm_movemask_pi8`
  --> /home/zhougj/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/packed_simd-0.3.3/src/codegen/reductions/mask/x86/sse.rs:47:21
   |
47 |                 use crate::arch::x86_64::_mm_movemask_pi8;
   |                     ^^^^^^^^^^^^^^^^^^^^^----------------
   |                     |                    |
   |                     |                    help: a similar name exists in the module: `_mm_movemask_epi8`
   |                     no `_mm_movemask_pi8` in `arch::x86_64`
   |
  ::: /home/zhougj/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/packed_simd-0.3.3/src/codegen/reductions/mask.rs:41:1
   |
41 | impl_mask_reductions!(m8x8);
   | ---------------------------- in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0432]: unresolved import `crate::arch::x86_64::_mm_movemask_pi8`
  --> /home/zhougj/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/packed_simd-0.3.3/src/codegen/reductions/mask/x86/sse.rs:62:21
   |
62 |                 use crate::arch::x86_64::_mm_movemask_pi8;
   |                     ^^^^^^^^^^^^^^^^^^^^^----------------
   |                     |                    |
   |                     |                    help: a similar name exists in the module: `_mm_movemask_epi8`
   |                     no `_mm_movemask_pi8` in `arch::x86_64`
   |
  ::: /home/zhougj/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/packed_simd-0.3.3/src/codegen/reductions/mask.rs:41:1
`

**Comment by rajasekarv** [comment]
can you pull the latest update and try compiling it?
