### ISSUE TITLE
'_mm_movemask_epi8' error

### ISSUE THREAD

**Issue by liergou99** [rajasekarv/vega#123]
error[E0432]: unresolved import `crate::arch::x86_64::_mm_movemask_pi8`
  --> /root/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/packed_simd-0.3.3/src/codegen/reductions/mask/x86/sse.rs:47:21
   |
47 |                 use crate::arch::x86_64::_mm_movemask_pi8;
   |                     ^^^^^^^^^^^^^^^^^^^^^----------------
   |                     |                    |
   |                     |                    help: a similar name exists in the module: `_mm_movemask_epi8`
   |                     no `_mm_movemask_pi8` in `arch::x86_64`
   | 
  ::: /root/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/packed_simd-0.3.3/src/codegen/reductions/mask.rs:41:1
   |
41 | impl_mask_reductions!(m8x8);
   | ---------------------------- in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by rajasekarv** [comment]
same issue as #122. can you please pull the latest update and try?

**Comment by zgjhust** [comment]
problem resolved after add the toolchain file

**Comment by liergou99** [comment]
There are new problems in the distributed mode of Vega：

thread 'tokio-runtime-worker' panicked at 'executor @15000 not initialized', /rustc/74e80468347471779be6060d8d7d6d04e98e467f/src/libstd/macros.rs:16:9

**Comment by liergou99** [comment]
thread 'tokio-runtime-worker' panicked at 'executor @15000 not initialized', /rustc/74e80468347471779be6060d8d7d6d04e98e467f/src/libstd/macros.rs:16:9
stack backtrace:
   0:     0x5557d1434035 - backtrace::backtrace::libunwind::trace::h508d2c55eb856ef2
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x5557d1434035 - backtrace::backtrace::trace_unsynchronized::h31c9d8a0097b92f8
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x5557d1434035 - std::sys_common::backtrace::_print_fmt::h520f528c4c103a3f
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5557d1434035 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf4dec5da8360bccb
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5557d146031c - core::fmt::write::hdf236390fbd68d3d
                               at src/libcore/fmt/mod.rs:1076
   5:     0x5557d142c7f3 - std::io::Write::write_fmt::hd33447f61d92a88a
                               at src/libstd/io/mod.rs:1537
   6:     0x5557d1436d40 - std::sys_common::backtrace::_print::h856c809943c588ab
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5557d1436d40 - std::sys_common::backtrace::print::hc042b4237cc3648a
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5557d1436d40 - std::panicking::default_hook::{{closure}}::h35997132c163f935
                               at src/libstd/panicking.rs:198
   9:     0x5557d1436a8c - std::panicking::default_hook::h8555bf398b0f1318
                               at src/libstd/panicking.rs:218
  10:     0x5557d1437377 - std::panicking::rust_panic_with_hook::h9b80e82887819c44
                               at src/libstd/panicking.rs:486
  11:     0x5557d1436f7b - rust_begin_unwind
                               at src/libstd/panicking.rs:388
