### ISSUE TITLE
Spark is a trademark of the Apache Software Foundation

### ISSUE THREAD

**Issue by jghoman** [rajasekarv/vega#27]
see: https://spark.apache.org/trademarks.html

**Comment by iduartgomez** [comment]
We shouldn't let this slide too long to avoid any sort of animosity towards the project. The action items would be:
* Choose a new name for the project (tough one).
* Update any mentions in the code comments or in documentation/readme to referee to Spark properly (eg. Apache Spark(tm)).
* In the future guarantee/enforce any mentions are done properly.

Is understandable we still want to maintain some sort of reference to the original project, so we can mention it by `framework inspired by Apache Spark(tm) `.  The profile of the project will be keep increasing as we do work and publish articles etc. so I wouldn't worry about it too much.

**Comment by steven-joruk** [comment]
Good plan of action. From what I've read referring to trademarks by their name without the trademark logo ("tm") is sufficient. Apache have guidance for [how to refer to their trademarks](https://www.apache.org/foundation/marks/).

**Comment by Yanwenjiepy** [comment]
Yes, these issues should be considered early

**Comment by burdges** [comment]
I think "fleck" and "flake" nicely parallels the noun usage of spark since rusted iron flakes off producing flecks of rust.  Also, rust starts where some protective layer flakes or flecks off, which parallels the verb usage.  I think both imply "numerous" or "clusters" as well as or better than spark.  "Fleck: Rust framework inspired by Apache Spark(tm)"

**Comment by rajasekarv** [comment]
Thanks for the suggestion @burdges . **Fleck, Bolt, Streak, Light, Photon** are the options for now. If we can reach a consensus on one of these, we can go ahead and rename the project.

**Comment by XVilka** [comment]
**Photon** is not an option - it's a famous [GUI subsystem from QNX](http://www.qnx.com/developers/docs/6.5.0/index.jsp?topic=%2Fcom.qnx.doc.neutrino_sys_arch%2Fphoton.html) and a registered trademark:
> Photon microGUI® for QNX® Neutrino®

**Comment by rajasekarv** [comment]
But this is not a competing/similar service to Photon. So does it still count as a trademark infringement?

**Comment by XVilka** [comment]
I don't know, just pointing out there is a well-known trademark with the same name.

**Comment by iduartgomez** [comment]
Fleck is very creative, but I also like Streak; those two are my favorite so far :)

**Comment by iduartgomez** [comment]
@rajasekarv maybe is a good time to move forward with this before we start adding a lot of configuration, documentation stuff etc. we would have to rename later? `Vega` is my favorite so far, or `nano` would also do.

**Comment by rajasekarv** [comment]
Going with Vega then. Will change it today

**Comment by ugoa** [comment]
Awesome. This finally happened.
Just out of curious, after the renaming would the old repo URL on the internet pointing to `native_spark` still works? Will they be redirected to the new `Vega` repo automatically by Github?

**Comment by rajasekarv** [comment]
Old repo URL will get redirected to this repo.
